In [211]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

### Loading the dataset

In [212]:
df_churn = pd.read_csv('Churn_Modelling.csv')
df_churn.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [213]:
df_churn.nunique()

RowNumber          10000
CustomerId         10000
Surname             2932
CreditScore          460
Geography              3
Gender                 2
Age                   70
Tenure                11
Balance             6382
NumOfProducts          4
HasCrCard              2
IsActiveMember         2
EstimatedSalary     9999
Exited                 2
dtype: int64

In this case, i'll drop the Surname column because it have 2932 unique qualitative variables

In [214]:
df_churn.drop('Surname', axis=1, inplace=True)
df_churn.drop('RowNumber', axis=1, inplace=True)
df_churn.drop('CustomerId', axis=1, inplace=True)
df_churn.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [215]:
print(pd.unique(df_churn['Geography']))

['France' 'Spain' 'Germany']

In [216]:
# Change qualitative variables
df_churn.loc[df_churn.Geography == "France", "Geography"] = 1
df_churn.loc[df_churn.Geography == "Spain", "Geography"] = 2
df_churn.loc[df_churn.Geography == "Germany", "Geography"] = 3

df_churn.loc[df_churn.Gender == "Female", "Gender"] = 1
df_churn.loc[df_churn.Gender == "Male", "Gender"] = 2
print(pd.unique(df_churn['Geography']))
print(df_churn.head())

[1 2 3]
   CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
0          619         1      1   42       2       0.00              1
1          608         2      1   41       1   83807.86              1
2          502         1      1   42       8  159660.80              3
3          699         1      1   39       1       0.00              2
4          850         2      1   43       2  125510.82              1

   HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          1               1        101348.88       1
1          0               1        112542.58       0
2          1               0        113931.57       1
3          0               0         93826.63       0
4          1               1         79084.10       0

In [217]:
Y = df_churn['Exited'].values
df_churn.drop('Exited', axis=1, inplace=True)
X = df_churn.values
print(Y.shape)
print(X.shape)

(10000,)
(10000, 10)

In [233]:
indexes = [0, 3, 5, 9]
for i in indexes:
    X[:,i] = X[:,i] / max(X[:,i])
    print(X[:,i])
X = X.astype(np.float32)

[0.7282352941176471 0.7152941176470589 0.5905882352941176 ...
 0.8341176470588235 0.908235294117647 0.9317647058823529]
[0.45652173913043476 0.44565217391304346 0.45652173913043476 ...
 0.391304347826087 0.45652173913043476 0.30434782608695654]
[0.0 0.33403147867725896 0.6363571759354565 ... 0.0 0.2992263113680937
 0.5187077749376251]
[0.5067634543058819 0.5627340588006109 0.5696792699405497 ...
 0.21043581238654574 0.46446006369839504 0.19096108013661311]

In [234]:
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.05)

In [235]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(9500, 10)
(9500,)
(500, 10)
(500,)

### Creating deep learning model

In [253]:
def classifier_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, activation='relu', input_shape=(1,10)),
        tf.keras.layers.Dense(5, activation='relu', input_shape=(1,10)),
        tf.keras.layers.Dense(1, activation='sigmoid', input_shape=(1,5)),
    ])

    return model

In [254]:
classifierModel = classifier_model()
opt = tf.keras.optimizers.Adam(
    learning_rate=0.0001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False)
classifierModel.compile(optimizer=opt,
                        loss='binary_crossentropy',
                        metrics=['accuracy']
                    )
classifierModel.build()

In [255]:
classifierModel.summary()

Model: "sequential_42"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_158 (Dense)            (None, 1, 10)             110
_________________________________________________________________
dense_159 (Dense)            (None, 1, 5)              55
_________________________________________________________________
dense_160 (Dense)            (None, 1, 1)              6
=================================================================
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________

In [256]:
history = classifierModel.fit(x=X_train, y=y_train, epochs=100)

Epoch 1/100
WARNING:tensorflow:Model was constructed with shape (None, 1, 10) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1, 10), dtype=tf.float32, name='dense_158_input'), name='dense_158_input', description="created by layer 'dense_158_input'"), but it was called on an input with incompatible shape (None, 10).
WARNING:tensorflow:Model was constructed with shape (None, 1, 10) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1, 10), dtype=tf.float32, name='dense_158_input'), name='dense_158_input', description="created by layer 'dense_158_input'"), but it was called on an input with incompatible shape (None, 10).
297/297 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7978
Epoch 2/100
297/297 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7978
Epoch 3/100
297/297 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7978
Epoch 4/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7978
Epoch 5/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7978
Epoch 6/100
297/297 [==============================] - 0s 2ms/step - loss: 0.4958 - accuracy: 0.7978
Epoch 7/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7978
Epoch 8/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7978
Epoch 9/100
297/297 [==============================] - 0s 2ms/step - loss: 0.4913 - accuracy: 0.7978
Epoch 10/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7978
Epoch 11/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7978
Epoch 12/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7979
Epoch 13/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7979
Epoch 14/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7978
Epoch 15/100
297/297 [==============================] - 0s 2ms/step - loss: 0.4827 - accuracy: 0.7978
Epoch 16/100
297/297 [==============================] - 0s 2ms/step - loss: 0.4815 - accuracy: 0.7978
Epoch 17/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7976
Epoch 18/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7976
Epoch 19/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4782 - accuracy: 0.7976
Epoch 20/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7977
Epoch 21/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4762 - accuracy: 0.7977: 0s - loss: 0.4799 - accuracy
Epoch 22/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4755 - accuracy: 0.7979: 0s - loss: 0.4764 - ac
Epoch 23/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4747 - accuracy: 0.7980
Epoch 24/100
297/297 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7979
Epoch 25/100
297/297 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7977: 0s - loss: 0.4686 - accuracy
Epoch 26/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4723 - accuracy: 0.7977
Epoch 27/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7979: 0s - loss: 0
Epoch 28/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7977
Epoch 29/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7979
Epoch 30/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7978
Epoch 31/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7974
Epoch 32/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7973: 0s - loss: 0.4612
Epoch 33/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4681 - accuracy: 0.7972
Epoch 34/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4677 - accuracy: 0.7977
Epoch 35/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7969
Epoch 36/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4669 - accuracy: 0.7980
Epoch 37/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4664 - accuracy: 0.7973
Epoch 38/100
297/297 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7977
Epoch 39/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4657 - accuracy: 0.7979
Epoch 40/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7977
Epoch 41/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4649 - accuracy: 0.7984
Epoch 42/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4645 - accuracy: 0.7986
Epoch 43/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7988
Epoch 44/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4637 - accuracy: 0.7986: 0s - loss: 0.4682 - ac
Epoch 45/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4633 - accuracy: 0.7992
Epoch 46/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4629 - accuracy: 0.7989
Epoch 47/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4625 - accuracy: 0.7987: 0s - l
Epoch 48/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4620 - accuracy: 0.7986
Epoch 49/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4616 - accuracy: 0.7989
Epoch 50/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4611 - accuracy: 0.7991
Epoch 51/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4606 - accuracy: 0.7994: 0s - loss: 0.4560 - accu
Epoch 52/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4601 - accuracy: 0.7988
Epoch 53/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7988
Epoch 54/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7988
Epoch 55/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4586 - accuracy: 0.7994
Epoch 56/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4581 - accuracy: 0.7997
Epoch 57/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4577 - accuracy: 0.8003: 0s - loss: 0.4568 - accuracy:
Epoch 58/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4572 - accuracy: 0.8001
Epoch 59/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4567 - accuracy: 0.8002: 0s - loss: 0.4516 - accuracy:  - ETA: 0s - loss: 0.4606 - accu
Epoch 60/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4563 - accuracy: 0.8006
Epoch 61/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.8001
Epoch 62/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.8008
Epoch 63/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4549 - accuracy: 0.8008
Epoch 64/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4546 - accuracy: 0.8011
Epoch 65/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4541 - accuracy: 0.8014
Epoch 66/100
297/297 [==============================] - 1s 4ms/step - loss: 0.4537 - accuracy: 0.8014
Epoch 67/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4532 - accuracy: 0.8016
Epoch 68/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4527 - accuracy: 0.8020
Epoch 69/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4523 - accuracy: 0.8015
Epoch 70/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4518 - accuracy: 0.8014
Epoch 71/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4514 - accuracy: 0.8015: 0s - l - ETA: 0s - loss: 0.4508 - accuracy: 0.80
Epoch 72/100

297/297 [==============================] - 1s 3ms/step - loss: 0.4509 - accuracy: 0.8023: 0s - loss: 0.4418 - accu
Epoch 73/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4505 - accuracy: 0.8017
Epoch 74/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4500 - accuracy: 0.8017
Epoch 75/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4495 - accuracy: 0.8015
Epoch 76/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4491 - accuracy: 0.8020
Epoch 77/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4487 - accuracy: 0.8023
Epoch 78/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4481 - accuracy: 0.8019: 0s - loss: 0.4501 - accu
Epoch 79/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4478 - accuracy: 0.8022
Epoch 80/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4472 - accuracy: 0.8023
Epoch 81/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4467 - accuracy: 0.8021
Epoch 82/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4463 - accuracy: 0.8026
Epoch 83/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4458 - accuracy: 0.8024
Epoch 84/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4453 - accuracy: 0.8032
Epoch 85/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4449 - accuracy: 0.8025
Epoch 86/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4443 - accuracy: 0.8029: 0s - loss: 0.442
Epoch 87/100
297/297 [==============================] - 1s 3ms/step - loss: 0.4439 - accuracy: 0.8032
Epoch 88/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4434 - accuracy: 0.8027
Epoch 89/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4429 - accuracy: 0.8025
Epoch 90/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4423 - accuracy: 0.8028: 0s - loss: 0.4450 - accura
Epoch 91/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4418 - accuracy: 0.8025
Epoch 92/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4413 - accuracy: 0.8036
Epoch 93/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4408 - accuracy: 0.8034
Epoch 94/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4402 - accuracy: 0.8051
Epoch 95/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4398 - accuracy: 0.8045
Epoch 96/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4392 - accuracy: 0.8059
Epoch 97/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4387 - accuracy: 0.8056
Epoch 98/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4381 - accuracy: 0.8064
Epoch 99/100
297/297 [==============================] - 1s 2ms/step - loss: 0.4375 - accuracy: 0.8069
Epoch 100/100
297/297 [==============================] - ETA: 0s - loss: 0.4363 - accuracy: 0.80 - 1s 2ms/step - loss: 0.4370 - accuracy: 0.8066